### Prefix key ###
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

### Splits ###
unbind '"'
unbind %
bind s split-window -v
bind v split-window -h

### Pane navigation (hjkl) ###
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

### Pane cycle (Shift+H / Shift+L) ###
bind H select-pane -t :.-
bind L select-pane -t :.+

### Mouse support ###
set -g mouse on

### Quality of life ###
set -sg escape-time 4 
setw -g mode-keys vi

# Terminal
set -g default-terminal "screen-256color"


bg="#1e1e2e"
panel="#181825"
fg="#cdd6f4"
muted="#7f849c"
accent="#89b4fa"
accent_soft="#6c7086"
border="#45475a"

setw -g pane-border-style "fg=$border"
setw -g pane-active-border-style "fg=$accent"
bind r source-file ~/.tmux.conf

set -g status on
set -g status-position bottom 
set -g status-style "fg=$fg,bg=$panel"
set -g status-interval 5
set -g status-right-length 90

set -g window-status-separator "  "

setw -g window-status-format \
"#[fg=$muted,bg=$panel] #I:#W "

setw -g window-status-current-format \
"#[fg=$accent,bg=$panel] *#I:#W "

set -g status-left ""

set -g status-right \
"#[fg=$accent_soft]│ \
#{?window_zoomed_flag,#[fg=$accent][Z] ,}\
#[fg=$muted]#(whoami) \
#[fg=$accent_soft]│ \
